//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEF.Models.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        internal int id;

        [Required(ErrorMessage = "Please provide ID")]
        public int ID { get; set; }
        [Required]
        [MaxLength(50, ErrorMessage = "Name must be Less than (Char)")]
        public string Name { get; set; }
        [Required]
        [MaxLength(50, ErrorMessage = "Fname must be Less than (Char)")]
        public string Fname { get; set; }

        [Required(ErrorMessage = "Please provide CGPA")]
        public double CGPA { get; set; }
    }
}
